const VALID_INPUT_FILE_EXTENSIONS = [".md", ".markdown"];
const VALID_SUMMARY_FILENAME_EXTENSIONS = [".json"];
const DEFAULT_OUTPUT_DIRECTORY = "output/all";
const DEFAULT_SUMMARY_OUTPUT_DIRECTORY = "output/summary";
const DEFAULT_SUMMARY_FILENAME = `summaryJSON${Date.now()}.json`;

exports.VALID_INPUT_FILE_EXTENSIONS = VALID_INPUT_FILE_EXTENSIONS;
exports.VALID_SUMMARY_FILENAME_EXTENSIONS = VALID_SUMMARY_FILENAME_EXTENSIONS;
exports.DEFAULT_OUTPUT_DIRECTORY = DEFAULT_OUTPUT_DIRECTORY;
exports.DEFAULT_SUMMARY_OUTPUT_DIRECTORY = DEFAULT_SUMMARY_OUTPUT_DIRECTORY;
exports.DEFAULT_SUMMARY_FILENAME = DEFAULT_SUMMARY_FILENAME; 